### ISSUE TITLE
Exception while attempting to configure plug-in

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jonfrink/confluence-cmis-plugin#3]
```
After installing the plug-in 
(cmis-confluence-plugin-1.1-20100607.214108-1-jar-with-dependencies.jar), I 
attempt to configure the plug-in.

Running Confluence 3.2.1_01 on Windows.


Here is a synopsis of the stack trace: 
 org.apache.velocity.exception.MethodInvocationException: Invocation of method 'hasObjectId' in class com.sourcesense.confluence.cmis.configuration.ConfigureCMISPluginAction threw exception java.lang.NullPointerException at /templates/cmis/configure-cmis.vm[line 70, column 132]
    at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:337)

caused by: java.lang.NullPointerException
    at com.sourcesense.confluence.cmis.configuration.ConfigureCMISPluginAction.hasObjectId(ConfigureCMISPluginAction.java:139) 
```

Original issue reported on code.google.com by `ben.switzer@gmail.com` on 24 Jun 2010 at 6:41

**Comment by GoogleCodeExporter** [comment]
```
I have encountered the same error while attempting to configure the plug-in in 
Confluence version 4.0. 
```

Original comment by `zhen...@gmail.com` on 21 Feb 2012 at 8:42
